s = str(input("Enter: "))
degreeloc = s.find(chr(176))
minuteloc = s.find("'")
secondloc = s.find('"')
degrees = float(s[:degreeloc])
minutes = float(s[degreeloc+1:minuteloc])
seconds = float(s[minuteloc+1:secondloc])
print(degrees)
print(minutes)
print(seconds)

d = float(input("Degrees: "))
m = float(input("Minutes: "))
s = float(input("Seconds: "))
decimaldegrees= d + (m/60) + (s/3600)
print(decimaldegrees)
#final
s = str(input("Enter: "))
degreeloc = s.find(chr(176))
minuteloc = s.find("'")
secondloc = s.find('"')
degrees = float(s[:degreeloc])
minutes = float(s[degreeloc+1:minuteloc])
seconds = float(s[minuteloc+1:secondloc])
decimaldegrees= degrees + (minutes/60) + (seconds/3600)
print(decimaldegrees)